version: '3.8'

services:
  invoice-app:
    build: .
    ports:
      - "5173:5173"
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
      - /app/node_modules
